services:
  postgres:
    image: postgres:16-alpine
    container_name: cesizen-postgres
    environment:
      POSTGRES_DB: cesizen
      POSTGRES_USER: cesizen
      POSTGRES_PASSWORD: cesizen
    ports:
      - "5432:5432"
    volumes:
      - cesizen_pg_data:/var/lib/postgresql/data

volumes:
  cesizen_pg_data:
